name: Build Electron Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    # --- TAMBAHKAN BAGIAN INI ---
    permissions:
      contents: write
    # ----------------------------

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Rebuild Native Modules
        run: bun run rebuild

      - name: Build React Frontend
        run: bun run build-react

      - name: Build and Release Electron App
        run: bun run buildwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}